"""initial relational schema

Revision ID: 36368bd3c193
Revises:
Create Date: 2026-08-27 16:59:06.902448
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "36368bd3c193"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("encrypted_totp_secret", sa.LargeBinary(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("remote_address", sa.String(length=64), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_attempt_lookup",
        "login_attempts",
        ["username", "remote_address", "attempted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_login_attempts_attempted_at"), "login_attempts", ["attempted_at"], unique=False
    )
    op.create_index(
        op.f("ix_login_attempts_remote_address"), "login_attempts", ["remote_address"], unique=False
    )
    op.create_index(
        op.f("ix_login_attempts_username"), "login_attempts", ["username"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled','revoked')", name="ck_users_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled','revoked')", name="ck_devices_status"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_devices_user_slug"),
    )
    op.create_index(op.f("ix_devices_status"), "devices", ["status"], unique=False)
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("administrator_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["administrator_id"], ["administrators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_sessions_administrator_id"), "sessions", ["administrator_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_revoked_at"), "sessions", ["revoked_at"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("administrator_id", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.CheckConstraint("outcome IN ('success','denied','failure')", name="ck_audit_outcome"),
        sa.ForeignKeyConstraint(["administrator_id"], ["administrators.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_actor_time", "audit_events", ["administrator_id", "occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_administrator_id"), "audit_events", ["administrator_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_device_id"), "audit_events", ["device_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False)
    op.create_table(
        "provisioning_packages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("includes_wireguard", sa.Boolean(), nullable=False),
        sa.Column("includes_vless", sa.Boolean(), nullable=False),
        sa.Column("encrypted_payload", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('ready','consumed','expired','purged')", name="ck_package_status"
        ),
        sa.CheckConstraint("includes_wireguard OR includes_vless", name="ck_package_has_protocol"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provisioning_packages_device_id"),
        "provisioning_packages",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provisioning_packages_expires_at"),
        "provisioning_packages",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provisioning_packages_status"), "provisioning_packages", ["status"], unique=False
    )
    op.create_table(
        "vless_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("client_uuid", sa.String(length=36), nullable=False),
        sa.Column("encrypted_client_uri", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("transmitted_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled','revoked')", name="ck_vless_status"),
        sa.CheckConstraint("received_bytes >= 0", name="ck_vless_received_nonnegative"),
        sa.CheckConstraint("transmitted_bytes >= 0", name="ck_vless_transmitted_nonnegative"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_uuid"),
        sa.UniqueConstraint("device_id"),
    )
    op.create_index(
        op.f("ix_vless_credentials_status"), "vless_credentials", ["status"], unique=False
    )
    op.create_table(
        "wireguard_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("public_key", sa.String(length=64), nullable=False),
        sa.Column("tunnel_address", sa.String(length=18), nullable=False),
        sa.Column("encrypted_client_config", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_handshake_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_bytes", sa.BigInteger(), nullable=False),
        sa.Column("transmitted_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled','revoked')", name="ck_wg_status"),
        sa.CheckConstraint("received_bytes >= 0", name="ck_wg_received_nonnegative"),
        sa.CheckConstraint("transmitted_bytes >= 0", name="ck_wg_transmitted_nonnegative"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
        sa.UniqueConstraint("public_key"),
        sa.UniqueConstraint("tunnel_address"),
    )
    op.create_index(
        op.f("ix_wireguard_credentials_status"), "wireguard_credentials", ["status"], unique=False
    )
    op.create_table(
        "one_time_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("package_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.CheckConstraint("attempts >= 0", name="ck_token_attempts_nonnegative"),
        sa.ForeignKeyConstraint(["package_id"], ["provisioning_packages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_one_time_tokens_consumed_at"), "one_time_tokens", ["consumed_at"], unique=False
    )
    op.create_index(
        op.f("ix_one_time_tokens_expires_at"), "one_time_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_one_time_tokens_package_id"), "one_time_tokens", ["package_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_one_time_tokens_package_id"), table_name="one_time_tokens")
    op.drop_index(op.f("ix_one_time_tokens_expires_at"), table_name="one_time_tokens")
    op.drop_index(op.f("ix_one_time_tokens_consumed_at"), table_name="one_time_tokens")
    op.drop_table("one_time_tokens")
    op.drop_index(op.f("ix_wireguard_credentials_status"), table_name="wireguard_credentials")
    op.drop_table("wireguard_credentials")
    op.drop_index(op.f("ix_vless_credentials_status"), table_name="vless_credentials")
    op.drop_table("vless_credentials")
    op.drop_index(op.f("ix_provisioning_packages_status"), table_name="provisioning_packages")
    op.drop_index(op.f("ix_provisioning_packages_expires_at"), table_name="provisioning_packages")
    op.drop_index(op.f("ix_provisioning_packages_device_id"), table_name="provisioning_packages")
    op.drop_table("provisioning_packages")
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_device_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_administrator_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_index("ix_audit_actor_time", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_sessions_revoked_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_administrator_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_status"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_login_attempts_username"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_remote_address"), table_name="login_attempts")
    op.drop_index(op.f("ix_login_attempts_attempted_at"), table_name="login_attempts")
    op.drop_index("ix_login_attempt_lookup", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_table("administrators")
    # ### end Alembic commands ###
